### ISSUE TITLE
Components that need styling

### ISSUE THREAD

**Issue by flachware** [zotero/reader#28]
- [x] Rework annotation design based on draft `annotation-4` #30.
- [x] Update annotation styles to clamped-view. #34 
- [x] Soften highlight color in PDF #32
- [x] Add color split button to page-popup #35
- [x] Search #38
- [x] Import bar #39
- [x] Error message #41
- [x] Note toggle icon (right sidebar)
- [ ] Down / focus state
- [ ] Page number editing
- [ ] Editor bubble
- [ ] Cursors in PDF viewer
- [ ] Loading bar
- [x] Blurred window state
- [ ] keyboard focus states in generic theme
- [ ] Update styles due to https://github.com/zotero/zotero-pdf.js/issues/10
- [ ] Hairline styles (toolbar buttons, search box, …) for generic theme on high-res displays
